### Recuperar todas las peliculas
GET http://localhost:1234/movies

### Recuperar peliculas por id
GET http://localhost:1234/movies/aa391090-b938-42eb-b520-86ea0aa3917b

### Recuperar todas las peliculas por un genero 
GET http://localhost:1234/movies?genre=Action

### Crear una pelicula
POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "The Lion King",
    "year": 1994,
    "director": "Roger Allers, Rob Minkoff",
    "duration": 88,
    "poster": "https://m.media-amazon.com/images/I/81BMmrwSFOL._AC_UF1000,1000_QL80_.jpg",
    "genre": [
        "Animation", "Adventure", "Drama"
    ]
    
}

### Borrar una pelicula
DELETE http://localhost:1234/movies/6a360a18-c645-4b47-9a7b-2a71babbf3e0

### actualizar una pelicula 
PATCH http://localhost:1234/movies/6a360a18-c645-4b47-9a7b-2a71babbf3e0
Content-Type: application/json

{
    "title": "pelicula actualizada",
    "year": 2011
}